protoc:
	protoc --go_out=. pb/order.proto
	@echo "Protoc file success!"

test:
	@echo "AAAAAAAAAAAA"

# swagger: 
# 	protoc --go_out=. pb/order.proto  
# 	@echo "Protoc file success!"


# docker: 
# 	protoc --go_out=. pb/order.proto  
# 	@echo "Protoc file success!"